export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;

export const REFRESH_TOKEN_BYTES = 32;
export const ROTATION_GRACE_MS = 30 * 1000;
export const MAX_ROTATE_ATTEMPTS = 2;

export const DEVICE_HEADER = 'x-device-name';
export const DEVICE_MAX_LENGTH = 100;
export const USER_AGENT_MAX_LENGTH = 256;

export const MAX_ACTIVE_SESSIONS = 10;

export const AUTH_ERROR = {
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',

  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKED: 'SESSION_REVOKED',

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
} as const;
