export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;

export const REFRESH_TOKEN_BYTES = 32;
export const ROTATION_GRACE_MS = 30 * 1000;
export const MAX_ROTATE_ATTEMPTS = 2;

export const MAX_ACTIVE_SESSIONS = 10;

export const AUTH_THROTTLE_TTL_MS = 60 * 1000;
export const AUTH_THROTTLE_LIMIT = 5;

export const LOGIN_FAILURE_THRESHOLD = 3;
export const LOGIN_BACKOFF_BASE_MS = 1000;
export const LOGIN_BACKOFF_MAX_MS = 5 * 60 * 1000;
export const LOGIN_FAILURE_DECAY_MS = 60 * 60 * 1000;

export const AUTH_AUDIT = {
  AUTHN_LOGIN: 'authn_login',
  AUTHN_LOGOUT: 'authn_logout',
  AUTHN_LOGIN_LOCK: 'authn_login_lock',
  SESSION_REVOKED: 'session_revoked',
  SESSION_TOKEN_REUSE: 'session_token_reuse',

  USER_CREATED: 'user_created',
  USER_REACTIVATED: 'user_reactivated',
} as const;

export const AUTH_ERROR = {
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_TEMPORARILY_LOCKED: 'ACCOUNT_TEMPORARILY_LOCKED',

  MISSING_TOKEN: 'MISSING_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKED: 'SESSION_REVOKED',

  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
} as const;
