export const COMMON_ERROR = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  NOT_FOUND: 'NOT_FOUND',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
  FOREIGN_KEY_CONSTRAINT: 'FOREIGN_KEY_CONSTRAINT',
} as const;
