export const FILE_UPLOAD_URL_TTL_SECONDS = 10 * 60;
export const FILE_DOWNLOAD_URL_TTL_SECONDS = 5 * 60;
export const FILE_COMPLETE_DEADLINE_MS = 15 * 1000;

export const FILE_IMAGE_MAX_EDGE = 2560;
export const FILE_NAME_MAX_LENGTH = 255;

export const FILE_PUBLIC_CACHE_CONTROL = 'public, max-age=31536000, immutable';
export const FILE_PRIVATE_CACHE_CONTROL = 'private, no-store';

export const FILE_THROTTLE_TTL_MS = 60 * 1000;
export const FILE_THROTTLE_LIMIT = 20;

export const FILE_PENDING_TTL_MS = 24 * 60 * 60 * 1000;
export const FILE_UNUSED_GRACE_MS = 24 * 60 * 60 * 1000;
export const FILE_SWEEP_BATCH_SIZE = 500;

export const FILE_JOB = {
  FILE_OBJECT_DELETE: 'file.object-delete',
  FILE_SWEEP: 'file.sweep',
} as const;

export const FILE_ERROR = {
  FILE_PURPOSE_UNKNOWN: 'FILE_PURPOSE_UNKNOWN',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_UPLOADED: 'FILE_NOT_UPLOADED',
  FILE_INVALID_CONTENT: 'FILE_INVALID_CONTENT',
  FILE_NOT_READY: 'FILE_NOT_READY',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  FILE_PROCESSING_BUSY: 'FILE_PROCESSING_BUSY',
} as const;
